#!/usr/bin/env bash

passwd_file="/etc/passwd"

if [ -f "$passwd_file" ]; then
    while IFS=: read -r username password uid gid info home shell; do
        group=$(getent group "$gid" | cut -d ':' -f 1)
        command=$(basename "$shell")
        echo "The user $username is part of the $group gang, lives in $home and rides $command."
        echo "User ID's place is protected by the passcode $password, more info about the user here: $uid $info"
        echo ""
    done < "$passwd_file"
else
    echo "Error: /etc/passwd file does not exist."
fi

