#!/usr/bin/env bash
# Displays numbers from 1 to 20
i=1
while [ "$i" -le 20 ]
do
	if [ "$i" -eq 4 ]
	then
		echo "bad luck from China"
	elif [ "$i" -eq 9 ]
	then
		echo "bad luck from Japan"
	else [ "$i" -eq 17 ]
		echo "bad luck from Italy"
	fi
	i=$(( i + 1 ))
done
