#!/usr/bin/env bash
# Display Best School 10 times
i=1
while [ "$i" -le 10 ]
do
	if [ "$i" -eq 4 ]
	then
		echo "bad luck from China"
	elif [ "$i" -eq 9 ]
	then
		echo "bad luck from Japan"
	else
		echo "bad luck from Italy"
	fi
	i=$(( i + 1 ))
done
