#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
# Displays hours from 0 to 12
# Displays minutes from 1 to 59

hour=0

while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    for minute in {1..59}; do
        echo $minute
        if [ $hour -eq 12 ] && [ $minute -eq 59 ]; then
            break 2
        fi
    done
    ((hour++))
done
