#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
# Displays hours from 0 to 12
# Displays minutes from 1 to 59

hours=0

while [ $hours -le 12 ]; do
	echo "Hour: $hour 1"
	minutes=1
	while [ $minutes -le 59 ]; do
        printf "%2d\n" $minutes
	(( minutes++ ))    
    done
    ((hours++))
done | head -n 71
