#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
# Displays hours from 0 to 12
# Displays minutes from 1 to 59

hour=0

while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    for minute in {1..59}; do
        echo $minute
    done
    ((hour++))
done | head -n 70
